export default {
    PORT: 8090,
    HTTP_PORT: 8091,
    REGION_SERVER_VERSION: "0.01",
    REGION_SERVER_KEY: "NodeBall-9a5d8e8a6fd255j8z5",
    MYSQL_HOST: "localhost",
    MYSQL_USER: "root",
    MYSQL_PASSWORD: "",
    MYSQL_DATABASE: "nodeball_test",

    STATS_COINS_BY_GOAL: 5,
    STATS_COINS_BY_ASSISTS: 3,
    STATS_COINS_BY_VICTORY: 10,
    STATS_COINS_BY_CS: 15,
    STATS_XP_BY_GOAL: 15,
    STATS_XP_BY_ASSISTS: 7,
    STATS_XP_BY_VICTORY: 35,
    STATS_XP_BY_CS: 45,
    STATS_MIN_ELO_PER_GAME: 50,
    STATS_MAX_ELO_PER_GAME: 20
}